language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  pip-compile --dry-run requirements.in | diff -u requirements.txt -
script:
  py.test -v --pep8 pelicanconf.py
