language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - pip install -U 'pip==8.1.1'
  - pip-compile -U -n requirements.in | diff -u requirements.txt -
script:
  py.test -v --pep8 pelicanconf.py
