language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
before_script:
  - pip install -U pip
  - pip-compile --no-header -U requirements.in
  - git diff --exit-code
script:
  pytest -v --pep8 pelicanconf.py
